(function(){"use strict";
var state={all:[],visible:[],selected:null,token:sessionStorage.getItem("sendora_admin_token")||""};
var statusLabels={new:"新询盘",whatsapp_clicked:"WhatsApp 已点击",contacted:"已联系",qualified:"有效询盘",quoted:"已报价",won:"已成交",lost:"未成交",spam:"垃圾询盘"};
var $=function(id){return document.getElementById(id)};
function text(value){return value===null||value===undefined||value===""?"—":String(value)}
function formatDate(value){if(!value)return "—";try{return new Intl.DateTimeFormat("zh-CN",{dateStyle:"medium",timeStyle:"short"}).format(new Date(value))}catch(_){return value}}
function pageName(value){try{var u=new URL(value);return u.pathname+(u.search||"")}catch(_){return text(value)}}
async function api(url,options){var requestOptions=Object.assign({},options||{}),showAuthError=requestOptions.showAuthError,headers=Object.assign({"Content-Type":"application/json"},requestOptions.headers||{});delete requestOptions.showAuthError;if(state.token)headers.Authorization="Bearer "+state.token;requestOptions.headers=headers;var response=await fetch(url,Object.assign({credentials:"same-origin"},requestOptions));var data=await response.json().catch(function(){return{}});if(response.status===401){state.token="";sessionStorage.removeItem("sendora_admin_token");showLogin();throw new Error(showAuthError?(data.message||"后台密码不正确。"):"请重新登录。")}if(!response.ok)throw new Error(data.message||"请求失败");return data}
function showLogin(){ $("dashboard").hidden=true;$("loginShell").hidden=false }
function showDashboard(){ $("loginShell").hidden=true;$("dashboard").hidden=false }
function el(tag,className,content){var node=document.createElement(tag);if(className)node.className=className;if(content!==undefined)node.textContent=content;return node}
function render(){var query=$("search").value.trim().toLowerCase();state.visible=state.all.filter(function(item){if(!query)return true;return [item.lead_ref,item.name,item.company,item.email,item.whatsapp_phone,item.current_page,item.first_landing_page,item.utm_term,item.utm_campaign].some(function(value){return String(value||"").toLowerCase().indexOf(query)!==-1})});
  var tbody=$("leadRows");tbody.replaceChildren();state.visible.forEach(function(item){var row=document.createElement("tr");var when=el("td","",formatDate(item.created_at));var customer=el("td");customer.append(el("strong","",text(item.lead_ref)),el("span","muted",[item.name,item.company,item.email].filter(Boolean).join(" · ")||"未识别客户（WhatsApp 点击）"));var channel=el("td");channel.append(el("span","badge "+item.conversion_type,item.conversion_type==="form"?"表单":"WhatsApp"));var source=el("td");source.append(el("strong","",text(item.source_type)),el("span","muted",item.utm_term?"关键词："+item.utm_term:(item.utm_campaign?"广告系列："+item.utm_campaign:"无可用关键词")));var landing=el("td");landing.append(el("span","",pageName(item.first_landing_page)),el("span","muted",item.visitor_country?[item.visitor_country,item.visitor_city].filter(Boolean).join(" / "):""));var status=el("td","",statusLabels[item.status]||item.status);var action=el("td");var button=el("button","link-button","查看");button.type="button";button.addEventListener("click",function(){openDetail(item)});action.append(button);row.append(when,customer,channel,source,landing,status,action);tbody.append(row)});$("emptyState").hidden=state.visible.length>0;updateMetrics()}
function updateMetrics(){var items=state.visible;$("metricTotal").textContent=items.length;$("metricNew").textContent=items.filter(function(x){return x.status==="new"}).length;$("metricForms").textContent=items.filter(function(x){return x.conversion_type==="form"}).length;$("metricWhatsapp").textContent=items.filter(function(x){return x.conversion_type==="whatsapp"}).length;$("metricRevenue").textContent=items.filter(function(x){return x.status==="quoted"||x.status==="won"}).length}
function detailRow(dl,label,value,asLink){var dt=el("dt","",label),dd=el("dd");if(asLink&&value){var a=el("a","",pageName(value));a.href=value;a.target="_blank";a.rel="noopener";dd.append(a)}else dd.textContent=text(value);dl.append(dt,dd)}
function openDetail(item){state.selected=item;var wrap=el("div","detail");wrap.append(el("p","eyebrow",item.conversion_type==="form"?"FORM INQUIRY":"WHATSAPP CLICK"),el("h2","",item.lead_ref));var intro=el("p","muted",formatDate(item.created_at)+" · "+text(item.source_type));wrap.append(intro);var dl=el("dl","detail-grid");detailRow(dl,"客户",[item.name,item.company].filter(Boolean).join(" / "));detailRow(dl,"邮箱",item.email);detailRow(dl,"WhatsApp / 电话",item.whatsapp_phone);detailRow(dl,"产品 / 数量",[item.product_type,item.quantity].filter(Boolean).join(" / "));detailRow(dl,"预算 / 目的地",[item.target_budget,item.delivery_destination].filter(Boolean).join(" / "));detailRow(dl,"需求",item.message);detailRow(dl,"来源",item.source_type);detailRow(dl,"UTM",[item.utm_source,item.utm_medium,item.utm_campaign,item.utm_term,item.utm_content].filter(Boolean).join(" / "));detailRow(dl,"广告点击 ID",item.gclid||item.fbclid||item.msclkid||item.ttclid);detailRow(dl,"首次入口页",item.first_landing_page,true);detailRow(dl,"询盘页面",item.current_page,true);detailRow(dl,"首次引荐",item.first_referrer,true);detailRow(dl,"浏览路径",item.page_history);detailRow(dl,"访客区域",[item.visitor_country,item.visitor_city,item.user_timezone].filter(Boolean).join(" / "));wrap.append(dl);var actions=el("div","detail-actions");var statusLabel=el("label","","状态"),select=el("select","status-select");Object.keys(statusLabels).forEach(function(value){var option=el("option","",statusLabels[value]);option.value=value;option.selected=value===item.status;select.append(option)});statusLabel.append(select);var notesLabel=el("label","","跟进备注"),notes=document.createElement("textarea");notes.value=item.notes||"";notes.placeholder="记录联系结果、报价进度或下次跟进事项";notesLabel.append(notes);var save=el("button","","保存");save.type="button";save.addEventListener("click",async function(){save.disabled=true;try{var result=await api("/api/admin-leads",{method:"PATCH",body:JSON.stringify({id:item.id,status:select.value,notes:notes.value,session_token:state.token})});Object.assign(item,result.inquiry||{status:select.value,notes:notes.value});render();$("detailDialog").close()}catch(error){alert(error.message)}finally{save.disabled=false}});actions.append(statusLabel,notesLabel,save);wrap.append(actions);$("detailContent").replaceChildren(wrap);$("detailDialog").showModal()}
async function load(){$("dashboardMessage").textContent="";try{var filters={};["status","type","source","from","to"].forEach(function(id){if($(id).value)filters[id]=$(id).value});var data=await api("/api/admin-leads",{method:"POST",body:JSON.stringify({session_token:state.token,filters:filters})});state.all=data.inquiries||[];render()}catch(error){$("dashboardMessage").textContent=error.message}}
function csvCell(value){var string=String(value===null||value===undefined?"":value);return '"'+string.replace(/"/g,'""')+'"'}
function exportCsv(){var fields=["created_at","lead_ref","conversion_type","status","name","company","email","whatsapp_phone","product_type","quantity","target_budget","delivery_destination","source_type","utm_source","utm_medium","utm_campaign","utm_term","first_landing_page","current_page","first_referrer","page_history","visitor_country","notes"];var rows=[fields.join(",")].concat(state.visible.map(function(item){return fields.map(function(field){return csvCell(item[field])}).join(",")}));var blob=new Blob(["\ufeff"+rows.join("\r\n")],{type:"text/csv;charset=utf-8"});var url=URL.createObjectURL(blob),a=document.createElement("a");a.href=url;a.download="sendora-inquiries-"+new Date().toISOString().slice(0,10)+".csv";a.click();URL.revokeObjectURL(url)}
$("loginForm").addEventListener("submit",async function(event){event.preventDefault();$("loginMessage").textContent="";try{var result=await api("/api/admin-auth",{method:"POST",body:JSON.stringify({password:$("password").value}),showAuthError:true});state.token=result.token||"";if(state.token)sessionStorage.setItem("sendora_admin_token",state.token);$("password").value="";showDashboard();await load()}catch(error){$("loginMessage").textContent=error.message}});$("logout").addEventListener("click",async function(){await api("/api/admin-auth",{method:"DELETE"}).catch(function(){});state.token="";sessionStorage.removeItem("sendora_admin_token");showLogin()});$("refresh").addEventListener("click",load);$("applyFilters").addEventListener("click",load);$("clearFilters").addEventListener("click",function(){["search","status","type","source","from","to"].forEach(function(id){$(id).value=""});load()});$("search").addEventListener("input",render);$("exportCsv").addEventListener("click",exportCsv);
if(state.token){showDashboard();load()}else{api("/api/admin-auth").then(function(){showDashboard();load()}).catch(function(){showLogin()})}
})();
